# Generated by Django 3.0.2 on 2020-01-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200128_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='company',
        ),
    ]
