# Generated by Django 3.0.2 on 2020-01-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_review_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.1.1', null=True),
        ),
    ]
