# Generated by Django 3.0.2 on 2020-01-28 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200128_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Company'),
        ),
    ]
