# Generated by Django 3.0.2 on 2020-01-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_review_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='company',
            field=models.IntegerField(),
        ),
    ]
