# Generated by Django 3.0.2 on 2020-01-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200128_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comp',
            field=models.ManyToManyField(to='api.Company'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='company',
        ),
        migrations.AddField(
            model_name='review',
            name='company',
            field=models.ManyToManyField(related_name='company', to='api.Company'),
        ),
    ]
