# Generated by Django 3.0.2 on 2020-01-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200128_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
