# Generated by Django 3.0.2 on 2020-01-29 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200129_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 9, 41, 18, 560240, tzinfo=utc)),
        ),
    ]
