# Generated by Django 3.0.2 on 2020-01-29 17:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_review_ips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='submission_date',
            field=models.DateTimeField(default=api.models.good_date),
        ),
    ]
