# Generated by Django 3.0.2 on 2020-01-31 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_animal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
